### ISSUE TITLE
404 errors browsing around

### ISSUE THREAD

**Issue by ghost** [sukria/WebKeePass#5]
~/WebKeePass$ date
tor 12 sep+ 2013 19.10.+58 CEST
~/WebKeePass$ git pull
Already up-to-date.

~/WebKeePass$ DANCER_PORT=3001 DANCER_ENVIRONMENT=xxx bin/app.pl

Then I go to myhost:3001 and press Database (top left), opens up myhost:3001/keepass and there I get a 404-error.

Error 404 - Not Found

/keepass
Powered by Dancer2 0.08

I then go back and login. That works fine. Now I'm at myhost:5001/keepass/keepass. I then press WebKeePass  (top left) and get the same 404-error.

Note, I have no integration with my regular http-server on this host (apache2). Maybe I am supposed to, it was mentioned in the blog post.

**Comment by sukria** [comment]
Maybe it's caused because of the name of your database, are you able to run all the tests?

$ prove -vl t/WebKeePass/DB.t

**Comment by ghost** [comment]
The name? 

~/WebKeePass$ prove -vl t/WebKeePass/DB.t 
t/WebKeePass/DB.t .. 
ok 1 - /home/xxx/WebKeePass/t/WebKeePass/../Test.kdbx exists
ok 2 - The object isa WebKeePass::DB
ok 3 - DB file opened with valid password
ok 4 - entries are parsed correclty
ok 5 - Got group by Test/Nested Groups
ok 6 - got group by Test/Nested Group/First
ok 7 - entry_by_id
not ok 8 - stats look fine

# Failed test 'stats look fine'

# at t/WebKeePass/DB.t line 106.

# Structures begin differing at:

# $got->{last_modified} = '2013-09-02 18:30:39'

# $expected->{last_modified} = '2013-02-24 15:13:05'

1..8

# Looks like you failed 1 test of 8.

Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/8 subtests 

## Test Summary Report

t/WebKeePass/DB.t (Wstat: 256 Tests: 8 Failed: 1)
  Failed test:  8
  Non-zero exit status: 1
Files=1, Tests=8,  0 wallclock secs ( 0.05 usr  0.03 sys +  0.36 cusr  0.14 csys =  0.58 CPU)
Result: FAIL

**Comment by keinkurt** [comment]
I have the same error and the same test error. But in my opinion, the test result doesn't related with this issue. What exactly has to be happen, if you click at the link 'Database'? I don't have find any GET-route '/keepass', only a POST-route for the ajax request.

**Comment by Tijojo** [comment]
As Keinkurt says, looks like you have to set a Get-route  for '/keepass'. 
I changed the line line 42 on lib/WebKeePass.pm like this : 

```
- post '/keepass' => sub {
+ any ['get', 'post'] => '/keepass' => sub {
```

And then it work for me

**Comment by sukria** [comment]
Indeed, that's a mistake in the view, I'm going to fix that.
